spring.application.name=backend

#----------------------------------------------------------------------
#           ESTO ES PA Q SPRINT HOOT DETECTE EL SV DEL PC
#----------------------------------------------------------------------

# Conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/wishdish
spring.datasource.username=root
spring.datasource.password=root

# Para que Spring Boot no se queje de configuraciones extra
spring.jpa.hibernate.ddl-auto=update

# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^