spring.application.name=backend

#----------------------------------------------------------------------
#           ESTO ES PA Q SPRINT HOOT DETECTE EL SV DEL PC
#----------------------------------------------------------------------

# Conexión a la base de datos MySQL
# Esta línea hace que la comunicación no esté cifrada de manera local. Si el sv da fallo descomentar.
# spring.datasource.url=jdbc:mysql://localhost:3306/wishdish?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.url=jdbc:mysql://localhost:3306/wishdish?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE (JPA)
# ===============================
# Evitamos que Java sobreescriba las tablas que creamos a mano
spring.jpa.hibernate.ddl-auto=none

# Mostrar en la consola las consultas SQL que hace Java (muy útil para buscar errores)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^